product_requirements_task:
  description: >
    As a Product Manager for a {theme} landing page:
    
    1. Topic Generation
       - Generate a unique, specific topic within the {theme} category
       - The topic should be a clear, specific title (not a placeholder)
       - Consider current trends and market opportunities
    
    2. Landing Page Type Definition
       - Determine the most suitable type (Blog, eCommerce, Service, etc.)
       - Justify the choice based on topic and target audience
       - Outline specific requirements for the chosen type
    
    3. Content Creation
       - Write compelling headline and subheadlines
       - Create all section content and CTAs
       - Develop unique value propositions
       - Write testimonials or social proof content
    
    4. Business Strategy
       - Define clear conversion goals
       - Identify target audience segments
       - Outline key performance metrics
    
    Your output MUST be formatted with clear section markers:
    
    TOPIC:
    [Generated unique topic name]
    
    PAGE_TYPE:
    [Landing page type and justification]
    
    CONTENT:
    [All page content organized by sections]
    
    STRATEGY:
    [Business goals and metrics]
  expected_output: >
    A comprehensive product specification including unique topic, page type,
    complete content, and business strategy for a {theme}-focused landing page.
  agent: product_manager

design_task:
  description: >
    As a UI/UX Designer for a {theme} landing page:
    
    1. Layout Innovation
       - Design a layout that best suits the landing page format
       - Create a distinctive hero section
       - Implement section arrangements that support the content flow
       - Design transitions that enhance the user journey
    
    2. Visual Hierarchy
       - Develop typography that reflects the {page_type} style
       - Create color combinations that resonate with the topic
       - Design components that support the content structure
       - Use white space to enhance readability
    
    3. Responsive Considerations
       - Design unique mobile-first interactions
       - Create distinctive tablet layouts (not just scaled versions)
       - Implement creative navigation patterns
       - Design unique content stacking for different breakpoints
    
    4. Component Innovation
       - Customize Bootstrap components with unique styling
       - Create distinctive hover/focus states
       - Design creative card layouts and list groups
       - Implement unique form styles
    
    5. Interactive Elements
       - Design creative micro-interactions
       - Plan unique scroll-based animations
       - Create distinctive call-to-action patterns
       - Implement innovative loading states
  expected_output: >
    A detailed design specification that pushes creative boundaries while maintaining
    usability, including unique layout patterns, custom component designs, and
    innovative responsive solutions using Bootstrap's framework.
  agent: ui_ux_designer

development_task:
  description: >
    As a Frontend Engineer for a {theme} landing page:
    
    1. Unique Bootstrap Customization
       - Customize components to match the requirements
       - Implement styles that enhance the presentation
       - Create variations that support the content structure
       - Design patterns that reflect the landing page type
    
    2. Creative Layout Implementation
       - Use Bootstrap's grid system in innovative ways
       - Implement unique responsive breakpoints
       - Create custom container variations
       - Design distinctive section transitions
    
    3. Performance Optimization
       - Implement lazy loading strategies
       - Optimize animation performance
       - Minimize CSS specificity conflicts
       - Ensure smooth mobile performance
    
    Your output MUST be formatted with clear section markers as follows:

    HTML:
    [Your HTML content here - focus on semantic structure and creative component usage]

    CSS:
    [Your CSS code here - include unique Bootstrap customizations and animations]

    JS:
    [Your JavaScript code here - implement creative interactions and optimizations]

    Each section must contain valid, well-formatted code that creates a unique user
    experience while maintaining Bootstrap's responsive features and accessibility.
  expected_output: >
    A complete, unique landing page implementation that extends Bootstrap's capabilities
    in creative ways while maintaining performance and accessibility.
  agent: frontend_engineer
