product_requirements_task:
  description: >
    Create detailed product requirements for a landing page focused on {topic}.
    Include sections on business goals, user needs, technical requirements, and key features.
    Consider current web design trends and best practices.
  expected_output: >
    A comprehensive product requirements document (PRD) with clear specifications for the landing page,
    including target audience, key features, technical constraints, and success metrics.
  agent: product_manager

design_task:
  description: >
    Based on the product requirements, create a detailed UI/UX design for the landing page.
    Focus on creating a responsive, user-friendly layout using Bootstrap 5 components.
    Include specifications for typography, color scheme, spacing, and interactive elements.
  expected_output: >
    A complete design specification document with wireframes, visual design elements,
    responsive layout details, and interaction patterns. Include Bootstrap 5 component recommendations.
  agent: ui_ux_designer

development_task:
  description: |
    As a frontend engineer, develop the landing page based on the provided design and requirements.
    
    Your output MUST be formatted with clear section markers as follows:
    
    HTML:
    [Your HTML code here]
    
    CSS:
    [Your CSS code here]
    
    JS:
    [Your JavaScript code here]
    
    Each section must contain valid, well-formatted code that follows best practices and implements the design requirements.
  expected_output: "A complete landing page implementation with HTML, CSS, and JavaScript code, properly formatted with section markers."
  agent: frontend_engineer
