product_requirements_task:
  description: >
    As a Product Manager for a {theme} landing page:
    
    1. Topic Generation
       - Generate a unique, specific topic within the {theme} category
       - The topic should be a clear, specific title (not a placeholder)
       - Consider current trends and market opportunities
    
    2. Landing Page Type Definition
       - Determine the most suitable type (Blog, eCommerce, Service, etc.)
       - Justify the choice based on topic and target audience
       - Outline specific requirements for the chosen type
    
    3. Content Creation
       - Write compelling headline and subheadlines
       - Create all section content and CTAs
       - Develop unique value propositions
       - Write testimonials or social proof content
    
    4. Business Strategy
       - Define clear conversion goals
       - Identify target audience segments
       - Outline key performance metrics
    
    Your output MUST be formatted with clear section markers:

    THEME:
    [Theme name]
    
    TOPIC:
    [Generated unique topic name]
    
    PAGE_TYPE:
    [Landing page type and justification]

    STRATEGY:
    [Business goals and metrics]
    
    CONTENT:
    [All page content organized by sections]
    
   
  expected_output: >
    THEME: [Theme name]
    TOPIC: [Generated unique topic name]
    PAGE_TYPE: [Landing page type and justification]
    STRATEGY: [Business goals and metrics]
    CONTENT: [All page content organized by sections]
  agent: product_manager

design_task:
  description: >
    You are a UI/UX Designer for a {theme} landing page.

    Create an innovative UI/UX design for the {topic} landing page that stands out while leveraging Bootstrap 5's capabilities. Focus on creating a unique visual identity that differentiates this landing page from common templates.

    You will reference Bootstrap v5 classes and components as much as possible.

    Your ONLY job is to create a technical design specification.
    
    YOU MUST OUTPUT IN THIS EXACT ORDER WITH THESE EXACT SECTION HEADERS:

    1. THEME:
    [Copy theme from Product Manager's requirements]
    
    2. TOPIC:
    [Copy topic from Product Manager's requirements]

    3. PAGE_TYPE:
    [Copy page type from Product Manager's requirements]
    
    4. CONTENT:
    [Copy all content from Product Manager's requirements, organized by section]

    5. LAYOUT:
    [Provide exact specifications for:
    - Hero section (exact height, width, padding in pixels)
    - Content sections (exact grid layout specifications)
    - Navigation structure (exact positioning and spacing)
    - Footer layout (exact measurements and structure)]

    6. VISUAL_DESIGN:
    [Provide exact specifications for:
    - Color palette (all hex codes required)
    - Typography (exact font sizes, weights, line heights)
    - Bootstrap V5 Component styles (exact border radius, shadows, etc.)
    - Spacing (exact margin and padding in pixels)]

    7. INTERACTIONS:
    [Provide exact specifications for:
    - Hover/focus states (exact color changes, transitions)
    - Animations (exact timing, easing functions)
    - Micro-interactions (exact behavior descriptions)
    - Loading states (exact animation specifications)]

    8. RESPONSIVE_DESIGN:
    [Provide exact specifications for:
    - Mobile layout (320px - 768px)
    - Tablet layout (768px - 1024px)
    - Desktop layout (1024px+)
    - Breakpoint-specific features]

    9. COMPONENTS:
    [Provide exact specifications for:
    - Navigation components (header, menu, dropdowns)
    - Hero section components (headlines, CTAs)
    - Content section components (cards, lists)
    - Call-to-action components (buttons, forms)
    - Form components (inputs, labels, validation)
    - Footer components (links, social icons)]

    IMPORTANT:
    - ALL nine sections are required
    - Follow the exact order shown above
    - Include ALL subsections
    - Use Bootstrap v5 classes and components as much as possible
    - Provide implementation-ready specifications
    - Include exact measurements in pixels
    - Include exact color codes
    - Frontend Engineer needs these exact details
  expected_output: >
    A complete technical design specification with ALL nine sections:
    THEME, TOPIC, PAGE_TYPE, CONTENT, LAYOUT, VISUAL_DESIGN, INTERACTIONS, RESPONSIVE_DESIGN, and COMPONENTS.
    Each section must contain detailed, implementation-ready specifications.
  agent: ui_ux_designer

development_task:
  description: >
    As a Frontend Engineer for a {theme} landing page, implement the UI/UX Designer's specifications following our standard landing page structure:

    REQUIRED SECTIONS (in order):
    1. Navigation Bar
       - Responsive navbar with logo and menu items
       - Mobile hamburger menu
       - Bootstrap navbar component

    2. Hero Section
       - Clear headline and subheadline
       - Primary CTA button
       - Optional hero image
       - Full-width container

    3. Features Section
       - Grid of feature cards
       - Icons or images
       - Bootstrap card components
       - Responsive grid layout

    4. How It Works / Process
       - Step-by-step explanation
       - Numbered or icon-based steps
       - Clear progression

    5. Footer
       - Copyright information
       - Additional links
       - Company information

    Your response must contain THREE sections:

    1. HTML SECTION:
    ```html
    <!-- Follow example template structure exactly -->
    ```

    2. CSS SECTION:
    ```css
    /* Custom styles and Bootstrap overrides */
    ```

    3. JS SECTION:
    ```javascript
    // Interactive elements and functionality
    ```

    IMPORTANT:
    - Reference the example template structure
    - Use semantic HTML5 elements
    - Implement all sections in order
    - Use Bootstrap 5 components
    - Follow accessibility best practices
  expected_output: >
    ONLY INCLUDE The Three complete code sections:
    1. HTML section using Bootstrap V5 classes and components
    2. CSS section with custom styles
    3. JS section with interaction code
    Each containing ONLY its respective language's CODE.
  agent: frontend_engineer
